# Server configuration
server:
  context-path: /micro
  port: 8080

# Spring properties
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://cap-sg-prd-4.securegateway.appdomain.cloud:19607/inventorydb
    username: dbuser
    password: inventorydb
  jpa:
    database: MYSQL

